### ISSUE TITLE
Problem with the example

### ISSUE THREAD

**Issue by alevittoria** [entronad/flutter_echarts#1]
Hello! The library is amazing but I must notify an error that made me lose 1 hour to understand why the library doesn't work.
In the example, the option terminates with the use of **;** and this breaks the chart.

**Comment by xxhh07** [comment]
Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91         is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86

**Comment by entronad** [comment]
@alevittoria 
Sorry about that. I have fixed that example in readme.
Thanks a lot!

**Comment by entronad** [comment]
@xxhh07 
example 在我的运行环境下并没有什么问题，不过安卓端的 app 编译过程确实会涉及到很多版本、兼容问题，建议你在自己的环境下建一个可运行的新 app，然后将 example 中的相关代码拷过去尝试运行。
