### ISSUE TITLE
Ugrade webview_flutter to 1.0.7 for better ios error detection

### ISSUE THREAD

**Issue by RickVM** [entronad/flutter_echarts#104]
As previously mentioned in some tickets I have some buggy behaviour when loading webviews, and thus flutter_echarts in IOS.
It seems to happen more often if there's multiple webviews, the view will be loaded blank. Refreshing helps, it seems like a 'chance' for things to go wrong.

Think its related to limitations in the flutter engine and IOS which are mentioned in [this issue](https://github.com/flutter/flutter/issues/61795)
A workaround has been implemented in the webview plugin as of 1.0.7 [here](https://github.com/flutter/plugins/pull/3212)

If we upgrade to the new version we should be able to implement the workaround to detect and handle issues for ios with WebView.onWebResourceError

Might be able to work on this issue this or next week, not sure yet if we should autoreload the webview if it was terminated, or let the user handle this with a callback parameter

**Comment by entronad** [comment]
Users of flutter_echarts mainly focus on charting.
They don't care about( or even don't know) the webview plugin under the hood. They just want the chart shown.
So I vote for the autoreload solution.

@RickVM , when implementing the autoreload, please be very careful to avoid an endless loop.

**Comment by GithubTeemo** [comment]
I put the initialization method in ``WidgetsBinding.instance.addPostFrameCallback``, it seems to solve this problem, but I feel that there will be jitter when the chart is loaded.

**Comment by lironzemingo** [comment]
> Users of flutter_echarts mainly focus on charting.
> They don't care about( or even don't know) the webview plugin under the hood. They just want the chart shown.
> So I vote for the autoreload solution.
> 
> @RickVM , when implementing the autoreload, please be very careful to avoid an endless loop.

what is the autoreload solution? We've been having problems with iPhones, not displaying the chart (iPhone 5 and 6)

**Comment by hakaari** [comment]
In my case as a temporary workaround getting rid of IndexedStack helped

**Comment by KoheiKanagu** [comment]
@RickVM 
I modified it so that it reloads when onWebResourceError is raised.
```pubspec.yaml
flutter_echarts:
  git:
    url: https://github.com/KoheiKanagu/flutter_echarts.git
    ref: feature/onWebResourceError
```

I'm testing this in my app, but if you want, you can try it to see if it solves the problem.
Note, however, that I have not taken any measures to prevent infinite loops.
We don't know if the infinite loop happens.

I used this as a reference
https://github.com/flutter/flutter/issues/61795#issuecomment-717608218

**Comment by KoheiKanagu** [comment]
https://github.com/entronad/flutter_echarts/issues/104#issuecomment-785690694

I'm still having problems with my app.

**Comment by pye52** [comment]
rollback flutter to 1.20.4, everything works fine.
在1.22之后的版本，webview flutter在ios上有很多问题…

**Comment by entronad** [comment]
Please update to v2.1.0 and try setting `reloadAfterInit` to `true`.
Details discussed in https://github.com/entronad/flutter_echarts/issues/124 .
