### ISSUE TITLE
pageView not showing 

### ISSUE THREAD

**Issue by JAICHANGPARK** [entronad/flutter_echarts#107]
First , Thanks for your works
I had some problem about showing chart in pageview

I am using an echart on two pages. There are cases when the chart cannot be displayed.

**Comment by figureai** [comment]
yep, I had some problem about showing chart in ListView.builder().

**Comment by entronad** [comment]
Please update to v2.1.0 and try setting `reloadAfterInit` to `true`.
Details discussed in https://github.com/entronad/flutter_echarts/issues/124 .
