### ISSUE TITLE
Update the echarts plugin from v4 to v5

### ISSUE THREAD

**Issue by singhtaranjeet** [entronad/flutter_echarts#109]
@entronad hey can you please update this package from v4 to v5?
#https://echarts.apache.org/en/tutorial.html#ECharts%205%20Upgrade%20Guide
Or provide us some way to use v5 charts.

**Comment by entronad** [comment]
After migrate to Echarts 5, some extensions is broken (I updated to the new extension versions too). Do you know why?

**Comment by singhtaranjeet** [comment]
No, I am not using the extensions so, i don't have any idea about them.
