### ISSUE TITLE
How can I apply dark palette for charts?

### ISSUE THREAD

**Issue by AeroAngel123** [entronad/flutter_echarts#11]
Echart website shows two other color palette along with default palette for charts. Is there a way we can utilize dark palette here in flutter_echarts? If so, how can we do it?

**Comment by entronad** [comment]
@AeroAngel123 

Good idea to make the theme configurable!
Thanks for reminding me that!
I have added this feature to import and set theme. Please upgrade flutter_echarts to version 1.3.0

Check the document in README.md -> Widget Properties -> theme
And a full example is here: https://github.com/entronad/flutter_echarts/blob/master/example/lib/main.dart#L333
