### ISSUE TITLE
Re-render after orientation change

### ISSUE THREAD

**Issue by tnusraddinov** [entronad/flutter_echarts#111]
Hello,
have a problem with echarts not re-render/expand after orientation change to landscape and vice versa?

![portrate](https://user-images.githubusercontent.com/7978543/107755578-113efe00-6d34-11eb-8cf9-0c46df7c9d30.png)

![landscape](https://user-images.githubusercontent.com/7978543/107755598-18660c00-6d34-11eb-851d-0b84f5c6db0d.png)

**Comment by tnusraddinov** [comment]
This should solve the problem, but how to access the webview controller?
```
await _controller.reload();
```

**Comment by KoheiKanagu** [comment]
@tnusraddinov 
Try specifying the GlobalKey.

```
OrientationBuilder(
  builder: (_, __) => SizedBox(
    height: 128,
    child: BarChartsWidget(
      key: GlobalObjectKey(
        MediaQuery.of(context).orientation,
      ),
    ),
  ),
),
```

```
class BarChartsWidget extends StatelessWidget {
  const BarChartsWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
	...

    return Echarts(
      option: jsonEncode(options),
    );
  }
}
```

**Comment by entronad** [comment]
Please update to v2.1.0. Now you can get `contorller` in the `onLoad` function.
