### ISSUE TITLE
图表渲染失败

### ISSUE THREAD

**Issue by pzc666** [entronad/flutter_echarts#114]
按照示例引入和使用、页面空白，图表未加载
import 'package:flutter_echarts/flutter_echarts.dart';

Container(
        color: Colors.red,
        child:  Echarts(
          option: '''
          option: {
            xAxis: {
              type: 'category',
              data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
            },
            yAxis: {
              type: 'value'
            },
            series: [{
              data: [820, 932, 901, 934, 1290, 1330, 1320],
              type: 'line'
            }]
          }
        ''',
        ),
        width: 300,
        height: 250,
      )

**Comment by entronad** [comment]
Please update to v2.1.0 and try setting `reloadAfterInit` to `true`.
Details discussed in https://github.com/entronad/flutter_echarts/issues/124 .

**Comment by akzhang** [comment]
> Please update to v2.1.0 and try setting `reloadAfterInit` to `true`.
> Details discussed in #124 .

it does't work yet. when I update to v2.1.0 and try setting 'reloadAfterInit' to true
