### ISSUE TITLE
Null-safety

### ISSUE THREAD

**Issue by saswatsaubhagya** [entronad/flutter_echarts#116]
Please update the package to null safety & web support. I wish to extend my hand towards it

**Comment by Okladnoj** [comment]
Is there an analogue. to support **Null-safety** and **Desktop**?

The developers have abandoned something this package

**Comment by entronad** [comment]
The v2.0.0 now supports null safey and Echarts 5.

This lib is based on webview, so only mobile is supported.
We know that a browser or a Windows OS dose not have a webview component :)
