### ISSUE TITLE
When I create APK file for my release chart is not appearing while during development everything is good!

### ISSUE THREAD

**Issue by sajjad-hk** [entronad/flutter_echarts#12]
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/something/Dev-tools/flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/something/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/something/Android/Sdk
    • Java binary at: /home/something/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6224510/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1)
    • Android Studio at /home/something/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6224510
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/something/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/193.6494.35
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • H8314 • BH900VN9BZ • android-arm64 • Android 10 (API 29)

**Comment by entronad** [comment]
@sajjad-hk 

In my case the released APK works as fine as debugging.
I can't reproduce your case.

**Comment by sajjad-hk** [comment]
I moved to 1.3.0 and also the issue was gone. But now I have another mild issue. The white screen before chart loads. Is there anyway to changed that

**Comment by entronad** [comment]
@sajjad-hk 
If "white screen" means the widget background (not the whole screen), I have to say it can not be solved now.
it's caused by a defect of webview_flutter that it forces the background to white, not tansparent or configurable. Some people have protested that,  and maybe this will change in future.
