### ISSUE TITLE
pub get failed (1; Because xxxxx_app depends on flutter_echarts >=2.0.0 which requires SDK version >=2.12.0 <3.0.0, version solving failed.)

### ISSUE THREAD

**Issue by lesliebigfans** [entronad/flutter_echarts#127]
I want to use flutter_echarts 2.1.0, when  I  run 'flutter pub get' and I got the error : 'pub get failed (1; Because xxxxl_app depends on flutter_echarts >=2.0.0 which requires SDK version >=2.12.0 <3.0.0, version solving failed.) '.
And the latest version of Flutter SDK is 2.0.5, what can I do to fix the error?

**Comment by entronad** [comment]
make sure your pubspec.yaml environment requirment greater than dart 2.12.0, witch supprts null-safety:
```
environment:
  sdk: ">=2.12.0 <3.0.0"
```

**Comment by lesliebigfans** [comment]
I set environment: sdk: ">=2.12.0 <3.0.0", when I run 'flutter pub get' and I got the another problem：
```
The current Dart SDK version is 2.10.5.                                 
                                                                        
Because xxx_app requires SDK version >=2.12.0 <3.0.0, version solving failed.
Running "flutter pub get" in xxx-application...                            
pub get failed (1; Because xxx_app requires SDK version >=2.12.0 <3.0.0, version solving failed.)
```

**Comment by entronad** [comment]
That means your flutter SDK version is too low, you have to insall the new version (flutter >= 2.0.0; dart >= 2.12.0)
