### ISSUE TITLE
曲线不显示

### ISSUE THREAD

**Issue by ruanjingwang** [entronad/flutter_echarts#13]
控制台显示
ViewRootImpl: jank_removeInvalidNode jank list is null

![image](https://user-images.githubusercontent.com/908034/76519207-85757f80-649b-11ea-8c50-532458f9ccc4.png)

**Comment by entronad** [comment]
@ruanjingwang 

没有遇到或被报过过这个问题过
你可以正常的运行本项目里的 example 吗？
