### ISSUE TITLE
手机屏幕切换横屏后，echarts宽度不变，怎么resize()

### ISSUE THREAD

**Issue by zhyhub** [entronad/flutter_echarts#144]
手机屏幕切换横屏后，echarts宽度不变，怎么resize()

**Comment by entronad** [comment]
由于 WebView 的功能限制，并不能监测到横竖屏变化，建议换用这个真 flutter 图表库 [Graphic](https://github.com/entronad/graphic)，可以自动响应widget的resize

**Comment by zhyhub** [comment]
好的 ，感谢
