### ISSUE TITLE
All charts are blank on iOS

### ISSUE THREAD

**Issue by dJani97** [entronad/flutter_echarts#153]
This may be related to https://github.com/entronad/flutter_echarts/issues/137

I had zero problems with the charts on Android devices.

But on iOS, the charts were not showing up in my own project, so I downloaded the example app and tried running it on my iPhone. But charts in the example app are also blank.

I've noticed that `reloadAfterInit: true` is not set in the examples, but even after setting it manually for all charts and restarting the entire app, the charts are still blank.

Flutter: `2.10.1`
Echarts: `2.3.0`
iOS: iPhone 7 is `15.1` and the Simulator is `15.2`

<table border="0">

<tr>
<th>iOS simulator</th>
<th>iPhone 7</th>
</tr>

<tr>
<td><img src="https://user-images.githubusercontent.com/22769564/155300458-980c8da9-0ff2-4aab-a368-a80e555a0dd4.png" alt="iOS"></td>
<td><img src="https://user-images.githubusercontent.com/22769564/155300542-11d9e62d-2d3e-4949-aba9-1dbbee73b021.png" alt="iOS"></td>
</tr>
	
</table>

**Comment by dJani97** [comment]
This may be related to https://github.com/entronad/flutter_echarts/issues/137

**Comment by entronad** [comment]
Please try v2.4.0

**Comment by dJani97** [comment]
Hey, thank you for the update and sorry for my late response.

I've tried running the latest example app on the same devices, and now it works on both!

_Note that I could only test it on iOS 15, I don't have access to iOS 16 yet._

**Comment by dJani97** [comment]
I'm pretty sure that this issue is a duplicate, I think you can close it too: https://github.com/entronad/flutter_echarts/issues/137

This may be related as well, but I'm not sure: https://github.com/entronad/flutter_echarts/issues/139
