### ISSUE TITLE
请升级下依赖,比如webview_flutter,谢谢

### ISSUE THREAD

**Issue by k3v1n-uncle** [entronad/flutter_echarts#154]

**Comment by gaoshan85** [comment]
After I upgraded webview_flutter to the latest 3.0.2,he graph cannot be displayed anymore.

**Comment by yuxingmin** [comment]
我也是想升级依赖，官方又不解决，你是怎么解决的？

**Comment by cn1001wang** [comment]
> After I upgraded webview_flutter to the latest 3.0.2,he graph cannot be displayed anymore.

I had the same problem. How did you solve the problem?

**Comment by entronad** [comment]
Upgraded in v2.4.0
