### ISSUE TITLE
get BufferQueueProducer print in console 

### ISSUE THREAD

**Issue by Ahmed20Salah** [entronad/flutter_echarts#16]
Hi there,
when i try to install Echarts it works fine but I get much of these warnings in the console :
D/BufferQueueProducer(28647): [SurfaceTexture-0-28647-0](this:0x9877a000,id:0,api:1,p:222,c:28647) cancelBuffer: slot 0
D/BufferQueueProducer(28647): [SurfaceTexture-0-28647-0](this:0x9877a000,id:0,api:1,p:222,c:28647) cancelBuffer: slot 2
D/BufferQueueProducer(28647): [SurfaceTexture-0-28647-0](this:0x9877a000,id:0,api:1,p:222,c:28647) cancelBuffer: slot 0
D/BufferQueueProducer(28647): [SurfaceTexture-0-28647-0](this:0x9877a000,id:0,api:1,p:222,c:28647) cancelBuffer: slot 2

like forever

**Comment by entronad** [comment]
@Ahmed20Salah 

I never met these infos, they seemed rather low-level and I don't know the meaning either...
