### ISSUE TITLE
webview_flutter ^4.0.1 no match

### ISSUE THREAD

**Issue by luodongwen** [entronad/flutter_echarts#177]
Because project flutter_echarts >=2.4.0 depends on webview_flutter ^3.0.4 and depends on webview_flutter ^4.0.1, flutter_echarts >=2.4.0 is forbidden.
So, because project depends on flutter_echarts ^2.4.0, version solving failed.
pub get failed (1; So, because flutter_gamsing_performer depends on flutter_echarts ^2.4.0, version solving failed.)

**Comment by sirkalmi** [comment]
This is causing me a problem too, I would be grateful if you could update the package.

**Comment by sirkalmi** [comment]
I did it.

https://github.com/sirkalmi/flutter_echarts.git

**Comment by kuma0605** [comment]
great job

**Comment by dJani97** [comment]
@sirkalmi can you create a PR into this repo? Maybe @entronad would review and merge it.

**Comment by entronad** [comment]
Please try v2.5.0:

- Upgrade webview_flutter to 4.2.4
- Upgrade Echarts to 5.4.3
- Upgrade SDK to >=2.12.0 <4.0.0
