### ISSUE TITLE
请升级下依赖,比如webview_flutter,谢谢

### ISSUE THREAD

**Issue by yuxingmin** [entronad/flutter_echarts#179]
能否更新依赖，webview_flutter ^3.0.4 to webview_flutter ^4.0.6
用户如何自己修改webview_flutter使用的版本

**Comment by kuma0605** [comment]
把github源码下下来,放到根目录下。
在yaml中，这样配置
`flutter_echarts:
    path: flutter_echarts`
这样，你就可以更改包代码了。

**Comment by entronad** [comment]
Please try v2.5.0:

- Upgrade webview_flutter to 4.2.4
- Upgrade Echarts to 5.4.3
- Upgrade SDK to >=2.12.0 <4.0.0
