### ISSUE TITLE
安卓加载时整个图表区域先闪一下黑色背景

### ISSUE THREAD

**Issue by slimcheng** [entronad/flutter_echarts#18]
echarts渲染出来以前，会在渲染区域闪一下黑色，这个有没有解决办法啊

**Comment by slimcheng** [comment]
> echarts渲染出来以前，会在渲染区域闪一下黑色，这个有没有解决办法啊
```
  extraScript: '''
       chart.on('rendered', () => {
            Messager.postMessage('rendered');
       });
```
配合Opacity解决了

**Comment by entronad** [comment]
@slimcheng 
你这个配合Opacity的方式在ios上有效吗
我试了一下android上可以ios上一直白的

**Comment by slimcheng** [comment]
> @slimcheng
> 你这个配合Opacity的方式在ios上有效吗
> 我试了一下android上可以ios上一直白的

iOS是有问题，做了个判断，只针对安卓做这个处理，iOS本身没有这个黑色背景的问题的

**Comment by entronad** [comment]
@slimcheng 
已将相关的逻辑加进到了库本身，请升级到 1.3.1，这样你不需要在外面写逻辑了

另外我试了下不需要等echarts加载完等消息通知再显示，那个黑闪非常短暂，onPageFinshed时显示就已经没有黑闪了，避免了一些通讯的逻辑

**Comment by slimcheng** [comment]
@entronad 
好的😄
