### ISSUE TITLE
各位大佬 WebView.destroy() called while WebView is still attached to window 这问题是怎么解决的。。。

### ISSUE THREAD

**Issue by zcd521** [entronad/flutter_echarts#187]

**Comment by maskxin** [comment]
升级库里面的webview_flutter

**Comment by zcd521** [comment]
Because flutter_echarts 2.4.0 depends on webview_flutter ^3.0.4 and no versions of flutter_echarts match >2.4.0 <3.0.0, flutter_echarts ^2.4.0 requires webview_flutter ^3.0.4.
flutter_echarts 的依赖是 3.0.4 版本

**Comment by zcd521** [comment]
> 升级库里面的webview_flutter

Because flutter_echarts 2.4.0 depends on webview_flutter ^3.0.4 and no versions of flutter_echarts match >2.4.0 <3.0.0, flutter_echarts ^2.4.0 requires webview_flutter ^3.0.4.
flutter_echarts 的依赖是 3.0.4 版本

**Comment by maskxin** [comment]
> > 升级库里面的webview_flutter
> 
> Because flutter_echarts 2.4.0 depends on webview_flutter ^3.0.4 and no versions of flutter_echarts match >2.4.0 <3.0.0, flutter_echarts ^2.4.0 requires webview_flutter ^3.0.4. flutter_echarts 的依赖是 3.0.4 版本

https://github.com/maskxin/flutter_echarts 用这个就行了

**Comment by entronad** [comment]
Please try v2.5.0:

- Upgrade webview_flutter to 4.2.4
- Upgrade Echarts to 5.4.3
- Upgrade SDK to >=2.12.0 <4.0.0
