### ISSUE TITLE
axis backgroud

### ISSUE THREAD

**Issue by lironiz** [entronad/flutter_echarts#19]
is there a way to give a background color for the whole area of the axis labels, instead of giving each axis label it's own background , which doesn't look good when scaling?

![image](https://user-images.githubusercontent.com/37082627/77323662-4c9c9c80-6d1e-11ea-872c-a122c9aede33.png)
in addition, I have this y axis on the left-
![image](https://user-images.githubusercontent.com/37082627/77324580-a2257900-6d1f-11ea-98ad-a562556def6e.png)

 and I want to give each label a different background, but that the background would take the entire label container, meaning each label will have 20% of the bg (5 labels). it doesn't work with this code of rich text :
`  rich:
                 {
                     One:
                     {
                      width: '20%',
                      height:27,
                        color:'#33334d',
                      fontSize: 12,
                         backgroundColor:'rgba(194, 156, 215, 0.8)',
                     },
                     
                     Two:{
                      width:'20%',
                      height:27,
                        color:'#33334d',
                      fontSize: 12,
                      backgroundColor:'rgba(210, 210, 210, 0.8)',
                     
                         }...,`

thank you.

**Comment by entronad** [comment]
@lironiz 

I really want to help but sorry I'm not an expert of echarts...
you can go to the main repo of echarts for help: https://github.com/apache/incubator-echarts
Within the Widget it's a pure echarts canvas, so any option config works in web will work here.
