### ISSUE TITLE
这库有极大的适配问题就不该去写出来的，早就该关闭了，

### ISSUE THREAD

**Issue by AlmostSir777** [entronad/flutter_echarts#192]
跟着这个库把echarts搞了一遍，快上线压测发现很多不显示空白的bug，有严重显示问题的库就不该一直留存，还靠着这个项目引流到自己的另外一个库，真是会坑死一批人。

**Comment by entronad** [comment]
您好，首先对您在使用 flutter_echarts 中遇到的问题表示歉意，对您提出的几点质疑澄清一下，希望取得您的理解：

1. 基于 Webview 的方案存在兼容性和性能问题，这一点在文档的开头就已经明确提示了。当然，这种提示可能不够醒目，再次表示歉意。

2. 存在兼容性和性能问题，为什么没有关闭呢？是因为这些问题主要见于复杂的、层叠的、重交互的页面中，而一些简单的 App 中使用 flutter_echarts 是没有问题的，所以这个库一直持续有使用者，这一点从 pub 上的下载分可以得到印证。
事实上在一年多前，出于和您类似的顾虑，我曾经 archive 了这个库，但是很多开发者在 issues 中提出了希望继续更新，并有人 fork 出来维护，因此后来我继续维护这个库，主要是跟进 Echarts 或 webview_flutter 的大版本，并 merge 一些 PR。

3. 能不能解决这些问题？自2018年这个库诞生以来，我本人以及很多积极参与者进行了很多尝试，虽然比早期版本优化了很多，但始终不能使它的性能与基于原生 flutter canvas 的可视化库看齐。而适配问题，由于手机系统碎片化，总是按下葫芦浮起瓢。我本人对此已使出浑身解数了，也许有高手能解决，如您有兴趣也欢迎您 PR。

4. 您“就不该去写出来的”这句话可真是把我逗乐了（无意冒犯），第一行代码写下之前，怎么能预知到 5 年后的适配问题呢。

5. 至于您提到的“还靠着这个项目引流到自己的另外一个库”，作为 Graphic 和 flutter_echarts 的作者，我非常确信 Graphic 优于 flutter_echarts，因此建议开发者使用前者而非后者。
我能听出您语气中对此的反感，但我不是太能理解您反感的原因。知识是在演进的，同一个开发者后开发的库应该是越来越好的，建议换新顺理成章。知名 Web 可视化项目 D3 的团队早年开发的库叫 Protovis ，后来他们开发了 D3，也在 Protovis 的文档开头建议开发者换用 D3，类似例子很多。

综上，您主张的 flutter_echarts 会”坑死一批人“，我属实不敢苟同。事实上在 flutter_echarts 发布至今的5年里我收到的更多的是开发者的肯定和建设性意见，反倒是假如我现在如您所说关闭该库会给不少开发者造成困扰。

从您描述的问题看，请不要再使用 flutter_echarts 了。虽然能感觉到您对我的不信任，但我还是诚恳的建议你看一下 Graphic，其他的 flutter 可视化库可能更加满足不了您的需求。祝您早日解决 bug 顺利上线！
