### ISSUE TITLE
在App上正常，但是在Flutter Web上报错，希望增加Web支持

### ISSUE THREAD

**Issue by mumushuiding** [entronad/flutter_echarts#20]
在App上正常，但是在Flutter Web上报错：Uncaught (in promise) Error: PlatformException(Unregistered factory, No factory registered for viewtype 'plugins.flutter.io/webview', null)

**Comment by entronad** [comment]
本项目目前仅可在移动端使用，
你的提议很好，我目前对 Flutter Web还不是非常了解，如何实现需要调研
