### ISSUE TITLE
Could not download guava.jar (com.google.guava:guava:26.0-jre)

### ISSUE THREAD

**Issue by function2000** [entronad/flutter_echarts#24]
**I try to run this examplle, but get below error, please support, thanks:**

* What went wrong:
A problem occurred configuring project ':webview_flutter'.
> Could not resolve all artifacts for configuration ':webview_flutter:classpath'.
   > Could not download guava.jar (com.google.guava:guava:26.0-jre)
      > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/26.0-jre/guava-26.0-jre.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/a0e9cabad665bc20bcd2b01f108e5fc03f756e13aea80abaadb9f407033bea2c?response-content-disposition=attachment%3Bfilename%3D%22guava-26.0-jre.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYTBlOWNhYmFkNjY1YmMyMGJjZDJiMDFmMTA4ZTVmYzAzZjc1NmUxM2FlYTgwYWJhYWRiOWY0MDcwMzNiZWEyYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmd1YXZhLTI2LjAtanJlLmphciUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4NTYzNzEzMH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=AmBLgQMHdkrkg6XNLlgbut1gDmSSzu-MQm7S0dxCvJFpZe3KCo-PQE5Sp6calp9nQa9BdQfld4sIRdGUnBw0Wmq6ohbHhOf2rLl~rXV18mjxAzeb4v3a-6-5GaMXYEFdTMT9DX4r5HsXikBOxSkPie~ZqM9lkb8yuWnLmCVJajrL~rvlt~7nez9WPOSPIp0Nr5q2SYmaC3JB3Z1ArzuAXcWhFKPSFCvluKPu1EOa28X9yWSgc5ygj2z1ylYVrIsOILsDHXeeKoPb-ZwjmBk0FeREnDaqqNY1GNJEllDMI1t6KCp7Lg01FVCwNaPMV8l6QUCeNztTUglGSScdFwaFDg__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.

**Comment by entronad** [comment]
It looks like an internet connection error in gradle.
I often meet with such problems if I forget to turn on the VPN.
Most of my cases is solved by trun on the VPN or to try more times
