### ISSUE TITLE
Can we use topojson instead on geojson file in echart map

### ISSUE THREAD

**Issue by jitenders859** [entronad/flutter_echarts#26]
I am trying to show population for all countries by states using topojson file in my flutter app. 
similar to https://echarts.apache.org/examples/en/editor.html?c=map-usa

geojson files are working but are very large compare and topojson files doesn't  is there a way to use topojson file in echarts 

if not I am not finding geojson file with smaller size for all countries can you please provide any source where I can find it geojson files of all countries with states.

as the example you have used 
the usa geojson filesize it small compare to what I am finding on internet.
http://echarts.apache.org/examples/data/asset/geo/USA.json

**Comment by entronad** [comment]
Sorry, I realy want to help but I'm not an expert of GIS. I'm not familiar with the json files you mationed.
Maybe you can get some help from the main repo of echarts: https://github.com/apache/incubator-echarts

**Comment by CiciIvory** [comment]
> Sorry, I realy want to help but I'm not an expert of GIS. I'm not familiar with the json files you mationed. Maybe you can get some help from the main repo of echarts: https://github.com/apache/incubator-echarts

你好 地图如何加进去呢 使用extensions没有效果
