### ISSUE TITLE
y轴数值显示不完整

### ISSUE THREAD

**Issue by mcxinyu** [entronad/flutter_echarts#27]
初始化y轴数值小时可以显示完整，当挪动底部 datazoom 时y轴数值变大就显示不完整了。
![image](https://user-images.githubusercontent.com/9566116/78622491-d66c6e00-78b7-11ea-92ab-5fff18cb8205.png)
![image](https://user-images.githubusercontent.com/9566116/78622502-e08e6c80-78b7-11ea-88e1-fded173cf5d0.png)

**Comment by andynvt** [comment]
try this one 
```
grid: {
     containLabel: true,
},
```

**Comment by mcxinyu** [comment]
Works great, thanks!
