### ISSUE TITLE
请求一下这个圆形的代码样式是在哪里实现的呀？

### ISSUE THREAD

**Issue by joyoes** [entronad/flutter_echarts#29]
![52347117-248ba480-2a5c-11e9-8402-5a94054dca50](https://user-images.githubusercontent.com/16605854/78760541-e79aa500-79b3-11ea-9bcd-68c4c6eaca3e.gif)
按这个圆形中的大小，应该是50%啊，怎么只有30%啊？能不能根据数字的大小，实现水量的大小啊？跪求一下实现代码，谢谢！

**Comment by entronad** [comment]
https://github.com/ecomfe/echarts-liquidfill
