### ISSUE TITLE
支持大数据量面积图吗

### ISSUE THREAD

**Issue by theecn** [entronad/flutter_echarts#31]

**Comment by entronad** [comment]
理论上 Echarts 及其扩展的所有功能都能实现，
具体数据量多大，在 WebView 上性能是否可接受需要具体测试

**Comment by theecn** [comment]
昨天测试了下---貌似不行

**Comment by entronad** [comment]
“大数据量面积图” 你指的是这个吗：https://gallery.echartsjs.com/editor.html?c=x8K2BwAFx5
这个示例就是一模一样的这个图：
https://github.com/entronad/flutter_echarts/blob/812347f2982fcdcfd1e39305afcf89337b409d77/example/lib/main.dart#L398
