### ISSUE TITLE
ListView中放多个图表，不可见区域有图片无法加载空白的情况

### ISSUE THREAD

**Issue by kazeik** [entronad/flutter_echarts#32]
在ListView中放多个图表，有柱形，曲线，或其它类型。
在界面初始化时，只加载了可见区域内的图表，不可见区域的未加载。
等滑动列表时，最初不可见区域内的是一个空白。
如果在图表初始化时迅速上下滑动列表，让不可见区域初始化一次后，图表将可以加载出来

**Comment by entronad** [comment]
例子中的 ListView 没有发生此现象
你是不是进行了什么异步加载的设置
能否提供更详细信息

**Comment by kazeik** [comment]
@entronad  我在模拟器中测试加载不出来，模拟器是iphone 6s 。然后换到安卓真机上，倒是可以加载。后续我没有追究这个问题了。

**Comment by 13213334722** [comment]
我碰到了类似的问题，我的图标放在listView的最下面，滑动到底部才能看到，但是加载不出来、或者说刷新不出来，是一个白色的区域，放到listView最上面，每次都能正常加载，正常显示
