### ISSUE TITLE
渲染速度慢

### ISSUE THREAD

**Issue by Abbykitty** [entronad/flutter_echarts#35]
在模拟器上图表初次渲染非常慢，大概十秒才渲染出来

**Comment by entronad** [comment]
建议在真机上测试一下是否满足性能需求。
debug 中的几个图表，包含3D的图表，在主流机型上大概是一秒多，总体 iOS 会比 android 快一些。

如果图表不复杂，对性能要求高建议使用其他 flutter 原生图表库
