### ISSUE TITLE
Flutter and Mobile devices

### ISSUE THREAD

**Issue by HuseyinAkkaya** [entronad/flutter_echarts#38]
Hello,
I use translation because I don't have English.
I am using echarts-gl surface with flutter. But the 'click' method does not work on mobile devices. 
It's your example: 
" 
extraScript: '''
  chart.on('click', (params) => {
    if(params.componentType === 'series') {
  	  Messager.postMessage('anything');
    }
  });
''',
"
But this code not working in surface with mobile devices.

Also, I cannot scroll the image in any direction. rotating by drag. How do I add scrool feature with double finger touch function?
Thank you.

**Comment by javadrajabi** [comment]
i have this problem

**Comment by entronad** [comment]
@HuseyinAkkaya 
@javadrajabi 

Did you find this issue on an iOS device?
Did you stack some widget that can capture gestures(such as a scrollview or a bottom) upon or under the chart?

I have noticed the issue that on some(maybe all) iOS device, when the chart stack on widget that can capture gestures, all gestrue recognizers will go wrong.
I have no idea to fix it yet. Maybe it's related to the WKWebview.

**Comment by javadrajabi** [comment]
find this issue on an Android device.
also
this issue just in 3d GL charts .
I checked andI realized that :
`
chart.on('click'....
`
this event not work. also this error is from the original library .
you can test it on this link 

https://echarts.apache.org/examples/en/editor.html

past this code on editor and run ...
`
var chart = echarts.init(document.getElementById("chart-panel"),"");
chart.on("click",(s)=>{
    alert(1);
});


option = {
    tooltip: {},
    backgroundColor: '#fff',
    visualMap: {
        show: false,
        dimension: 2,
        min: -1,
        max: 1,
        inRange: {
            color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
        }
    },
    xAxis3D: {
        type: 'value'
    },
    yAxis3D: {
        type: 'value'
    },
    zAxis3D: {
        type: 'value'
    },
    grid3D: {
        viewControl: {
            // projection: 'orthographic'
        }
    },
    series: [{
        type: 'surface',
        wireframe: {
            // show: false
        },
        equation: {
            x: {
                step: 0.05
            },
            y: {
                step: 0.05
            },
            z: function (x, y) {
                if (Math.abs(x) < 0.1 && Math.abs(y) < 0.1) {
                    return '-';
                }
                return Math.sin(x * Math.PI) * Math.sin(y * Math.PI);
            }
        }
    }]
}
`
this code is for web browser.
this code work on desktop device when you click on chart show alert but just not work on mobile device.
not work on flutter and not work in web browser (inmobile device)
I think the two are related

**Comment by javadrajabi** [comment]
https://github.com/apache/incubator-echarts/issues/12496
