### ISSUE TITLE
chart.on(“click” not work on phone device

### ISSUE THREAD

**Issue by javadrajabi** [entronad/flutter_echarts#40]
when create gl 3d chart dont work on phone this code but this work on desktop.

var chart = echarts.init(document.getElementById('chart-panel'),'');

chart.on("click", (myScript) => {

  alert(myScript);
});

this code add to the first of the code in this page https://echarts.apache.org/examples/en/editor.html?c=simple-surface&gl=1

this code just work on desktop device

**Comment by entronad** [comment]
We also observed that in some rare cases(most in iOS), when the chart is stacked with gesture detector widgets in phone devices, both gestures will fail.
We still don't know why and how to solve.
