### ISSUE TITLE
严重错误   在Sliver 中 添加多个图表 利用 Swiper 进行划分   进行滑动 会出现闪退

### ISSUE THREAD

**Issue by sanrixue** [entronad/flutter_echarts#45]
0 Flutter | flutter::FlutterPlatformViewsController::CompositeEmbeddedView(int) + 1964
-- | --
1 Flutter | flutter::FlutterPlatformViewsController::CompositeEmbeddedView(int) + 1960
2 Flutter | flutter::IOSSurfaceGL::CompositeEmbeddedView(int) + 80
3 Flutter | flutter::PlatformViewLayer::Paint(flutter::Layer::PaintContext&) const + 48
4 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
5 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
6 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
7 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
8 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
9 Flutter | flutter::ClipRectLayer::Paint(flutter::Layer::PaintContext&) const + 208
10 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
11 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
12 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
13 Flutter | flutter::ClipRectLayer::Paint(flutter::Layer::PaintContext&) const + 208
14 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
15 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
16 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
17 Flutter | flutter::ClipRectLayer::Paint(flutter::Layer::PaintContext&) const + 208
18 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
19 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
20 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
21 Flutter | flutter::PhysicalShapeLayer::Paint(flutter::Layer::PaintContext&) const + 432
22 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
23 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
24 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
25 Flutter | flutter::ClipRectLayer::Paint(flutter::Layer::PaintContext&) const + 208
26 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
27 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
28 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
29 Flutter | flutter::ClipRectLayer::Paint(flutter::Layer::PaintContext&) const + 208
30 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
31 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
32 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
33 Flutter | flutter::PhysicalShapeLayer::Paint(flutter::Layer::PaintContext&) const + 432
34 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
35 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
36 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
37 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
38 Flutter | flutter::ContainerLayer::PaintChildren(flutter::Layer::PaintContext&) const + 88
39 Flutter | flutter::TransformLayer::Paint(flutter::Layer::PaintContext&) const + 136
40 Flutter | flutter::CompositorContext::ScopedFrame::Raster(flutter::LayerTree&, bool) + 808
41 Flutter | flutter::Rasterizer::DrawToSurface(flutter::LayerTree&) + 456
42 Flutter | _ZNSt3__110__function6__funcIZN7flutter10Rasterizer4DrawEN3fml6RefPtrINS2_8PipelineINS2_9LayerTreeEEEEEE3$_0NS_9allocatorISA_EEFvNS_10unique_ptrIS7_NS_14default_deleteIS7_EEEEEEclEOSG_ + 104
43 Flutter | flutter::Rasterizer::Draw(fml::RefPtr<flutter::Pipeline<flutter::LayerTree> >) + 476
44 Flutter | _ZNSt3__110__function6__funcIZN7flutter5Shell14OnAnimatorDrawEN3fml6RefPtrINS2_8PipelineINS2_9LayerTreeEEEEEE4$_28NS_9allocatorISA_EEFvvEEclEv + 76
45 Flutter | fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 132
46 Flutter | fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 32
47 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
48 CoreFoundation | ___CFRunLoopDoTimer + 880
49 CoreFoundation | ___CFRunLoopDoTimers + 276
50 CoreFoundation | ___CFRunLoopRun + 1640
51 CoreFoundation | CFRunLoopRunSpecific + 424
52 GraphicsServices | GSEventRunModal + 160
53 UIKitCore | UIApplicationMain + 1932

**Comment by entronad** [comment]
flutter 中并无名为 Sliver 的组件，你是想指 SliverList 还是 SliverAppBar 吗？
flutter 中并无名为 Swiper 的组件

你具体指的什么可否上个代码看下

**Comment by sanrixue** [comment]
SliverList

**Comment by sanrixue** [comment]
另 在项目中嵌入map 滚动时 时常会发生滑动被阻断的情况

**Comment by entronad** [comment]
目前来看，webview_flutter，或者可能更底层的 platform_view 在比较复杂的 widget 代理创建、手势拾取方面是有些 bug，在 flutter_echarts 的代码层面难以解决，建议这种情况下用原生的可视化库（比如 charts_flutter）

**Comment by sanrixue** [comment]
是的 已经切换到手绘部分 但 需求有中国地图 功能 需要echarts

**Comment by sanrixue** [comment]
滚动截断问题 可通过 升级到最新1.17.1 即可解决
