### ISSUE TITLE
iOS chart is getting stuck/hang

### ISSUE THREAD

**Issue by codenamics** [entronad/flutter_echarts#46]
Hello,

Flutter 1.7.1

when i test charts features chart stuck or hang and i cannot do anything.

import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';

import 'package:flutter_echarts/flutter_echarts.dart';
import 'package:number_display/number_display.dart';

final display = createDisplay(decimal: 2);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();

  List<Map<String, Object>> _data1 = [{ 'name': 'Please wait', 'value': 0 }];

  getData1() async {
    await Future.delayed(Duration(seconds: 4));

    const dataObj = [{
      'name': 'Jan',
      'value': 8726.2453,
    }, {
      'name': 'Feb',
      'value': 2445.2453,
    }, {
      'name': 'Mar',
      'value': 6636.2400,
    }, {
      'name': 'Apr',
      'value': 4774.2453,
    }, {
      'name': 'May',
      'value': 1066.2453,
    }, {
      'name': 'Jun',
      'value': 4576.9932,
    }, {
      'name': 'Jul',
      'value': 8926.9823,
    }];

    this.setState(() { this._data1 = dataObj;});
  }

  @override
  void initState() {
    super.initState();

    this.getData1();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: Text('Echarts Demon'),
      ),
      backgroundColor: Colors.white,
      body: Center(
        child: Column(
          children: <Widget>[
       
            Container(
              child: Echarts(
                option: '''
                  {
                    dataset: {
                      dimensions: ['name', 'value'],
                      source: ${jsonEncode(_data1)},
                    },
                    tooltip: {
      trigger: 'axis',
       
    },
          
                  dataZoom: [{
      type: 'inside',
      start: 0,
      end: 10
    }, {
      start: 0,
      end: 100,
      handleIcon: 'M10.7,11.9v-1.3H9.3v1.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4v1.3h1.3v-1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
      handleSize: '100%',
      handleStyle: {
          color: '#fff',
          shadowBlur: 3,
          shadowColor: 'rgba(0, 0, 0, 0.6)',
          shadowOffsetX: 2,
          shadowOffsetY: 2
      }
    }],
                    color: ['#3398DB'],
                    legend: {
                      data: ['直接访问', '背景'],
                      show: true,
                    },
                    grid: {
                      left: '0%',
                      right: '0%',
                      bottom: '5%',
                      top: '7%',
                      height: '85%',
                      containLabel: true,
                      z: 22,
                    },
                    xAxis: [{
                      type: 'category',
                      gridIndex: 0,
                      axisTick: {
                        show: true,
                      },
                      axisLine: {
                        lineStyle: {
                          color: '#000',
                        },
                      },
                      axisLabel: {
                        show: true,
                        color: 'rgb(170,170,170)',
                        formatter: function xFormatter(value, index) {
                          if (index === 6) {
                            return `\${value}\\n*`;
                          }
                          return value;
                        },
                      },
                    }],
                    yAxis: {
                      type: 'value',
                      gridIndex: 0,
                      splitLine: {
                        show: false,
                      },
                      axisTick: {
                          show: false,
                      },
                      axisLine: {
                        lineStyle: {
                          color: '#0c3b71',
                        },
                      },
                      axisLabel: {
                        color: 'rgb(170,170,170)',
                      },
                      splitNumber: 12,
                      splitArea: {
                        show: true,
                        areaStyle: {
                          color: ['rgba(250,250,250,0.0)', 'rgba(250,250,250,0.05)'],
                        },
                      },
                    },
                    series: [{
                      name: '合格率',
                      type: 'line',
                      barWidth: '50%',
                      xAxisIndex: 0,
                      yAxisIndex: 0,
                      itemStyle: {
                        normal: {
                          barBorderRadius: 5,
                          color: {
                            type: 'linear',
                            x: 0,
                            y: 0,
                            x2: 0,
                            y2: 1,
                            colorStops: [
                              {
                                offset: 0, color: '#00feff',
                              },
                              {
                                offset: 1, color: '#027eff',
                              },
                              {
                                offset: 1, color: '#0286ff',
                              },
                            ],
                          },
                        },
                      },
                      zlevel: 11,
                    }],
                  }
                ''',
                extraScript: '''
                  chart.on('click', (params) => {
                    if(params.componentType === 'series') {
                      Messager.postMessage(JSON.stringify({
                        type: 'select',
                        payload: params.dataIndex,
                      }));
                    }
                  });
                ''',
                onMessage: (String message) {
                  Map<String, Object> messageAction = jsonDecode(message);
                  print(messageAction);
                  if (messageAction['type'] == 'select') {
                    final item = _data1[messageAction['payload']];
                    _scaffoldKey.currentState.showSnackBar(
                      SnackBar(
                        content: Text(item['name'].toString() + ': ' + display(item['value'])),
                        duration: Duration(seconds: 2),
                      ));
                  }
                },
              ),
              width: 500,
              height: 500,
            ),
           
          
           
           
          ],
        ),
      ),
    );
  }
}

**Comment by entronad** [comment]
1. Did this occures in iOS 13, but works well in lower iOS ?
2. Did you put the chart on/under any gesture ditector(ScrollView, Button, GestureDetector)
3. Did this happened only after you touched the chart (or something near the chart)?
