### ISSUE TITLE
Cannot change size of chart

### ISSUE THREAD

**Issue by kaciula** [entronad/flutter_echarts#47]
Wrapping the chart widget in a SizedBox with a specific height does not work as expected. The chart stays the same natural height no matter the value I provide. Here are some screenshots. The 2 color bands mark the top and bottom of the SizedBox that contains the chart widget.

![device-2020-05-25-170336](https://user-images.githubusercontent.com/18688/82819909-e3661080-9ea9-11ea-8d4f-09ebaf24d62d.png)

![fill_space](https://user-images.githubusercontent.com/18688/82819580-44d9af80-9ea9-11ea-9340-6287a4f5adf4.png)

**Comment by mellowcello77** [comment]
This seems to be a powerful package, would like to know the answer to this too.

**Comment by marcel-bluestone** [comment]
I do experience the same challenge. I need the chart to adapt to the parent's size. This does not seem to work. 
Is there a way to set the width & height of the chart to be rendered as an option?

**Comment by entronad** [comment]
Please update to v2.1.0. Now you can get `contorller` in the `onLoad` function.
`controller.reload()` in a proper time in the outer widgets may solve your problem.
Details disscused in https://github.com/entronad/flutter_echarts/issues/111 .
