### ISSUE TITLE
Chart doesn't redraw in realtime if inside a scrollable widget

### ISSUE THREAD

**Issue by sezaru** [entronad/flutter_echarts#5]
Hello there, first of all, amazing library :)

Whenever I add a chart to some scrollable widget, like `SingleChildScrollView` the chart stops being "realtime" responsive.

For example, if I have a candlestick chart (like this one https://www.echartsjs.com/examples/en/editor.html?c=candlestick-touch ) and want to move the chart data, it will not redraw the chart in realtime, it will only redraw after I release the click.

The chart works as expected if I insert it not inside a scrollable widget.

**Comment by sezaru** [comment]
An update, It seems to be a bug from flutter_webview, this is the issue link https://github.com/flutter/flutter/issues/35394

There is a workaround in this link, I tried it and it works (I'm not sure if this break something else) you can see the workaround in my fork here: https://github.com/sezaru/flutter_echarts/commit/ba2ec2b2e5dbe8ec1222b25150ab2c4cfa38e21a

**Comment by entronad** [comment]
@sezaru 

Thanks for your work!
I haven't considered the gesture conflict thoroughly.

Would you make a Pull request and then I shall test and publish it

**Comment by sezaru** [comment]
Sure! I will just be traveling for 2 weeks from today, so I will probably be able to create the PR when I'm back.

**Comment by entronad** [comment]
@sezaru 
Er... 2 weeks may be a little too long.
If it's not convenient for you to commit the PR today, I would manually copy the changes from your code for a quick fix version.

**Comment by sezaru** [comment]
Sure thing, go ahead :)
Sorry for that, it was a last-minute business trip.

**Comment by entronad** [comment]
@sezaru 
Handled. I added a property `captureAllGestures` to trigger it because some users may want the containers not the charts to act.

Please update to 1.2.0, and add `captureAllGestures: true`.
