### ISSUE TITLE
如何显示和关闭loading效果

### ISSUE THREAD

**Issue by xhanb** [entronad/flutter_echarts#50]
如何和异步接口协作，获取数据前显示loading，结束后关闭loading?
目前只能通过以下方式显示loading
 extraScript: '''
  chart.showLoading();
'''

**Comment by entronad** [comment]
这个需求我建议你放在外面做，图表本身不含loading的图标，在图表组件上叠一个其他 flutter widget 用来显示或隐藏 loading的图标
