### ISSUE TITLE
flutter_echarts 中加入map

### ISSUE THREAD

**Issue by sanrixue** [entronad/flutter_echarts#52]
在sliver中加入 echarts 如果不放大没问题； 但是加入  roam: true,  可放大参数后 会使得页面卡死

**Comment by entronad** [comment]
WebView 的性能和稳定性受图表复杂程度、扩展插件、页面组件结构影响较大，建议仅在实际效果达到预期时使用，对于性能要求较高的情况改用dart原生的方案（如 https://pub.dev/packages/charts_flutter）
