### ISSUE TITLE
图表要一定的时间才能渲染显示

### ISSUE THREAD

**Issue by LNyears** [entronad/flutter_echarts#53]
我能否知道什么时候图表已经准备好要显示了

**Comment by entronad** [comment]
onLoad 参数

**Comment by AAChartModel** [comment]
因为模拟器上 WebView 加载 HTML 和 JavaScript 文件需要一段时间, 在真机上效果会好很多,几乎就是即时加载,用户很难感知的到

**Comment by LNyears** [comment]
我就是用的真机运行的demo哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An An"<notifications@github.com&gt;; 
发送时间: 2020年6月19日(星期五) 上午10:26
收件人: "entronad/flutter_echarts"<flutter_echarts@noreply.github.com&gt;; 
抄送: "N year"<1353382535@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [entronad/flutter_echarts] 图表要一定的时间才能渲染显示 (#53)





 
因为模拟器上 WebView 加载 HTML 和 JavaScript 文件需要一段时间, 在真机上效果会好很多,几乎就是即时加载,用户很难感知的到

**Comment by entronad** [comment]
flutter_echarts 使用的是 WebView 加载 js 的方式实现功能的，在性能和可靠性上毫无疑问是比不上 dart 原生的实现方式。
实际的加载速度受图表的复杂程度、扩展插件、页面上图表的数量、设备等多种因素影响差别很大，
所以建议使用时进行充分测试，仅在性能和稳定性满足预期要求的情况下使用。
对于不太复杂且性能要求高的情况，建议使用 https://pub.dev/packages/charts_flutter

**Comment by sanrixue** [comment]
charts_flutter 并不能满足需求  项目需求是需要中国地图进行渲染的  但有时候就是白屏
