### ISSUE TITLE
How to pass variable into extraScript String

### ISSUE THREAD

**Issue by huiwen0212** [entronad/flutter_echarts#55]
Hi Everyone, I am trying create a candlestick chart, but currently the graph is not generated when I pass an variable with jsonEncode into the splitData function, if I hardcode the list into the splitData function it works. (The graph data is from Server)

![image](https://user-images.githubusercontent.com/49686493/84930899-8e15cb80-b104-11ea-9b5d-eef63526daf9.png)
![image](https://user-images.githubusercontent.com/49686493/84930986-ad145d80-b104-11ea-8eb9-a5e51584f78f.png)

**Comment by entronad** [comment]
To change the data, I suggest to pass the new data to the widget param "option". This is the same as the best way suggested by the  echarts team.
