### ISSUE TITLE
Update chart in flutter

### ISSUE THREAD

**Issue by lironiz** [entronad/flutter_echarts#56]
Hello,
I would like to dynamically update the dataset of my flutter_echart. I'm looking the way to call this function:
_function addData(chart, label, data) {
    chart.data.labels.push(label);
    chart.data.datasets.forEach((dataset) => {
        dataset.data.push(data);
    });
    chart.update();
}_

**without rebuilding the entire chart, just animate the graph with the new data:**
is there a way to run scripts in 'extraScript' after the chart was generated?

**Comment by entronad** [comment]
You just need to change the dataset passed to the "option" param, the widget will automatically get the difference and execute setOption, and the echarts will update the series, not rebuild the chart.

**Comment by lironiz** [comment]
thank you for the quick reply.
do you mean that I need if I have a
```
var chartOption = getOption();
Echart myChart = Echarts(
           option: option,
            extraScript: ExtraScripts.getChartEvents(false),
           onMessage: ...
    );
```

then when I get the updated data, I should fetch the new option String with the new data - 
`chartOption = getOption();`
and echart will update the series?
because the Echart instance doesn't have a setter for option.

**Comment by entronad** [comment]
Yes, just make sure the new chartOption string is diffrent to the old chartOption string.
The widget will detect the diffrence and call the js chart.setOption() method in the onUpdate lifecircle.
In echarts if you need to set a new option and trigger the update, you need to call the setOption method, not the option setter.

**Comment by xelons** [comment]
How do you pass data from Flutter to javascript?

**Comment by entronad** [comment]
@xelons 
Pass a new option with your new data
