### ISSUE TITLE
请问如何对flutter_echart进行截图

### ISSUE THREAD

**Issue by aiyouBug** [entronad/flutter_echarts#58]
在使用过程中发现用RepaintBoundary包裹Echarts获得的是一张空白的图片
RepaintBoundary(
          key: globalKey,
          child: Container(
              color: Colors.white,
              width: duSetWidth(375),
              height: duSetHeight(350),
              child: Echarts(
                option: '''
                    {
                      tooltip:{
                        trigger: 'item',
                        formatter: '{b}: {c} ({d}%)'
                      },
                     
                      backgroundColor: "#fff",
                      color: ${jsonEncode(colorList)},
                      legend: {
                        show: true,
                        bottom: '3%',
                      },
                      series: [{
                        label: {
                          show: false
                        },
                        labelLine: {
                          show: false
                        },
                        type: 'pie',
                        center: ['50%', '35%'],
                        radius: ['40%', '60%'],
                        show: false,
                        data:${jsonEncode(_data)},
                      }],
                    }
                  ''',
                extraScript: '''
                    chart.on('click', (params) => {
                      if(params.componentType === 'series') {
                        Messager.postMessage(JSON.stringify({
                          type: 'select',
                          payload: params.dataIndex,
                        }));
                      }
                    });
                  ''',
              )
          ),
        )

**Comment by entronad** [comment]
flutter_echarts 是基于webview而不是customPaint进行绘图的，不可用此方法截图
目前没有截图的功能
