### ISSUE TITLE
iOS 13.5.1  图表左右滑动或者放大之后，无法继续滑动或者缩小，图表卡住了。另12.4系统没有此问题，麻烦看下此问题

### ISSUE THREAD

**Issue by walkerwg** [entronad/flutter_echarts#61]

**Comment by entronad** [comment]
是否有报错信息

**Comment by walkerwg** [comment]
没有报错，页面可以正常返回，但是图标卡住了，我使用了datazoom配置，试着了改了下参数还是不行，删除此配置就可以了

**Comment by walkerwg** [comment]
控制台打印：Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by entronad** [comment]
Did you put the chart on/under any gesture ditector(ScrollView, Button, GestureDetector)

**Comment by MagicalWater** [comment]
同样遇到此问题, 在 iOS 13.5.1 的系统上
在较低的系统上是没问题的

现在只要滑一下或者放大缩小, 则整个元件会卡住
元件并无放置于任何会抓取手势的元件底下

**Comment by yy1234** [comment]
同样问题，在iphone7上是卡顿的，在x上是好的，性能问题？

**Comment by entronad** [comment]
有关卡顿、有时渲染不出、点击无效的问题，可能是 webview 在 ios 上表现的问题。
目前只有期待 webview 本身的更新优化
