### ISSUE TITLE
有时候画图会出现白屏，数据是有的，就是白屏

### ISSUE THREAD

**Issue by chenxilu0505** [entronad/flutter_echarts#62]

**Comment by wanghaiyang5241** [comment]
可以考虑用图表完成事件来触发遮罩显示或者隐藏

**Comment by wanghaiyang5241** [comment]
onMessage: (String message) {
            //EasyLoading.dismiss();
            if (!mounted) return;
            setState(() {
              loading1.isLoadingFinish = true;
            });
          },
          extraScript: '''
          chart.on('finished', function () {
              Messager.postMessage('ok');
          });
''',

**Comment by jiasu-hezhip** [comment]
Are you not shown in the route? There is no white screen problem by placing the page in the first loaded route
