### ISSUE TITLE
flutter_echarts1.2.0 在iphone6 plus上不显示，错误提示：chart.setOption is not a function

### ISSUE THREAD

**Issue by fengbo102** [entronad/flutter_echarts#7]
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=TypeError: chart.setOption is not a function. (In 'chart.setOption', 'chart.setOption' is undefined), WKJavaScriptExceptionSourceURL=data:text/html;base64,ICAgIDwhRE9DVFlQRSBodG1sPgogICAgPGh0bWw+CiAgICAgIDxoZWFkPgogICAgICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij ... PgogIA==, NSLocalizedDescription=A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber=22})
	0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
	1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
	<asynchronous suspension>
	2      MethodChannelWebViewPlatform.evaluateJavascript (package:webview_flutter/src/webview_method_channel.dart:95:21)
	3      WebViewController.evaluateJavascript (package:webview_flutter/webview_flutter.dart:655:39)
	4      _EchartsState.init (package:flutter_echarts/flutter_echarts.dart:112:24)
	5      _EchartsState.echartWidget.<anonymous closure> (package:flutter_echarts/flutter_echarts.dart:141:9)
	6      _PlatformCallbacksHandler.onPageFinished (package:webview_flutter/webview_flutter.dart:481:15)
	7      MethodChannelWebViewPlatform._onMethodCall (package:webview_flutter/src/webview_method_channel.dart:41:35)
	8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
	9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
	10     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
	11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
	12     _rootRun (dart:async/zone.dart:1126:13)
	13     _CustomZone.run (dart:async/zone.dart:1023:19)
	14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
	15     _invoke3 (dart:ui/hooks.dart:302:10)
	16     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)

**Comment by entronad** [comment]
@fengbo102 
你操作系统是哪个版本？
在较新的机型上（比如iPhone 11）上是否有问题

**Comment by fengbo102** [comment]
@entronad 
操作系统： mac os 10.14.6
在较新的机型上（比如iPhone 11）没有问题， 在iphone6s也没有问题；
仅在iphone6 plus上发现了该问题。

**Comment by fengbo102** [comment]
@entronad 
操作系统： ios 10.3.1 
在较新的机型上（比如iPhone 11）没有问题
专门下载了10.3的模拟器去测试iphone6， iphone6 plus， iphone6s， iphone7都有这个问题。

**Comment by entronad** [comment]
@fengbo102 

较老的机型上找不到 chart.setOption 应该是脚本来不及加载完引起的。
按照 webview_flutter 的说明 onPageFinished 会在所有脚本加载完之后才执行，
但这里可能因为老的机器无法在合适的时间内加载完脚本提前触发 onPageFinished ，
也可能与 webview_flutter 在 ios 上现存的一些问题有关 https://github.com/flutter/flutter/issues/47677

目前 ios 端的 webview_flutter 在加载和触发 onPageFinished 的行为上比较诡异，没有特别好的解决方案，我会密切关注它的改进。

**Comment by fengbo102** [comment]
@entronad 问题找到了， const chart = echarts.init(document.getElementById('chart'), null); 
将const改为var就可以了， ios旧版本对const支持不太好。

**Comment by entronad** [comment]
@fengbo102 

将这个改动加入了，请更新到 1.2.1 试一下是否可行。

**Comment by fengbo102** [comment]
@entronad  1.2.1 在ios10.3.1上测试通过；ios版本也测试没问题

**Comment by entronad** [comment]
@fengbo102 
谢谢！
