### ISSUE TITLE
onMessage from Flutter to Javascript

### ISSUE THREAD

**Issue by xelons** [entronad/flutter_echarts#75]
Hi,

The example shows how to send data from Javascript to Flutter, but what about the other way around?
I need to send data from Flutter to Javascript, to update dynamic graph series.

I can access initial value only using ${widget.dateData}, but I can't update the data.

Thanks.

**Comment by entronad** [comment]
Just update the data in the option, the chart will diff and setOption automatically.

You can refer to the first chart in the example app:
https://github.com/entronad/flutter_echarts/blob/2b09061c1f94a287e39567556311b6423adf7096/example/lib/main.dart#L88

**Comment by xelons** [comment]
Thanks, that worked.
