### ISSUE TITLE
How to add image figure on candle chart layer on specific candle?

### ISSUE THREAD

**Issue by hayashi-tz** [entronad/flutter_echarts#79]
Dear developers,

May I kindly know, how to add an image figure on the candle chart layer on a specific candle? I would like to add some profile images and a triangle icon on the candle.

I am looking forward to your reply and support.

Thank you very much in advance!

**Comment by entronad** [comment]
I think you are talking about this : https://echarts.apache.org/en/option.html#series-candlestick.markPoint

Remenber that in Flutter, as you can not get your app assets path from the webview, you must first transform you image to base64 like `'image://data:image/gif;base64,......`

**Comment by hayashi-tz** [comment]
Dear Developers,

Thank you very much for supporting me.

If possible, is there any simple or example using mark points on the candlestick chart?

Thank you!

**Comment by hayashi-tz** [comment]
I got the solution. Thank you very much!

**Comment by entronad** [comment]
You can get all examples form the official site of Echarts: https://echarts.apache.org/examples/en/index.html
