### ISSUE TITLE
 apply load until running the graph

### ISSUE THREAD

**Issue by jheimes-silveira** [entronad/flutter_echarts#8]
would I like to draw a load with a complete boot component, any listening function or finish loading the object?

**Comment by entronad** [comment]
@jheimes-silveira 
Flutter_echarts dosen't have this feature for now.
May I ask why you need such feature, I don't see such features in other charting libaries?

**Comment by entronad** [comment]
@jheimes-silveira 

I have added a param `onLoad`, maybe it's what you need.
