### ISSUE TITLE
Can able to add rectangle, triangle and some figure in chart?

### ISSUE THREAD

**Issue by hayashi-tz** [entronad/flutter_echarts#80]
Dear Developers,

I would like to add some figure/ shape in the chart and also when zooming and sliding, the figure will move to belong to the chart.
Here is an example link and screenshot.

https://charting-library.tradingview.com/

![Screen Shot 2020-10-01 at 2 42 50 PM](https://user-images.githubusercontent.com/32185240/94784805-b0520180-03f4-11eb-9c59-f7049bffeb48.png)

There is some feature in echart please kindly tell me how to use it?

I am looking forward to your reply and support.

Thank you very much.

**Comment by entronad** [comment]
Is this option satisfying you?: https://echarts.apache.org/en/option.html#graphic

Maybe you can start an issue in https://github.com/apache/incubator-echarts , there are more experts of Echarts there

**Comment by hayashi-tz** [comment]
Thank you very much for your reply.
