### ISSUE TITLE
Update flutter_webview version

### ISSUE THREAD

**Issue by RickVM** [entronad/flutter_echarts#88]
flutter_echarts currently uses developer preview version 0.3
Flutter_webview has been updated to out of developer preview 1.0.5.
This version no longer requires adding a key to info.plist and is stated to have better performance for IOS, for which  coincidentally i'm currently having problems. (3/5 times the webview renders blank.)

see: https://pub.dev/packages/webview_flutter/changelog

Shall I test it and create a pull request?

**Comment by RickVM** [comment]
I have tested the update and created a new pull request.
No problems found.

https://github.com/entronad/flutter_echarts/pull/89

Unfortunately the screen still ocassionaly render blank for the ios version

**Comment by entronad** [comment]
Yes, the new version of webview seems still not stable enough ...
