### ISSUE TITLE
切换页面会导致webview重新加载

### ISSUE THREAD

**Issue by pmlican** [entronad/flutter_echarts#9]
app底下有4个tabbar按钮，切换页面时会导致webview重新加载白屏
![12.gif](https://i.loli.net/2020/02/27/V7x1Wdjc8uPYrNm.gif)

**Comment by pmlican** [comment]
找到原因了，是我没搞懂widget的状态，用IndexedStack套一层就可以了

**Comment by entronad** [comment]
@pmlican 
你动图中描述的加载时白一下，是因为现在 webview_flutter 组件的背景颜色强制为白色，因此在加载出来之前组件会是白色，已经有人提了希望 webview_flutter 组件可配置背景颜色或改为透明背景，在这之前没有很好的解决办法
