### ISSUE TITLE
Horizontal scroll is not smooth

### ISSUE THREAD

**Issue by Ghost180195** [entronad/flutter_echarts#95]
I use echart on page which is long and has vertical scroll. But in this scenario echart with horizontal scroll can't be scrolled smooth

**Comment by entronad** [comment]
Please try the new params captureHorizontalGesture or captureVerticalGesture in new 1.5.0 version. Maybe that will handle your issue.

**Comment by Ghost180195** [comment]
Ok, thanks. I will try it

**Comment by Ghost180195** [comment]
@entronad 
Where should I add captureHorizontalGesture? Can you help with an example?
I have such code:
`
import "package:flutter/material.dart";
import 'package:flutter_echarts/flutter_echarts.dart';

class EchartTemperature extends StatefulWidget {
  @override
  _EchartTemperatureState createState() => _EchartTemperatureState();
}

class _EchartTemperatureState extends State<EchartTemperature> {
  int _minTemperature = 37;
  int _maxTemperature = 41;
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Echarts temperature'),
      ),
      body: Container(
        height: 400,
        child: Echarts(
          option: '''
            {
             tooltip: {
                trigger: 'axis'
              },
              legend: {
                            data: ['One', 'Two', 'Three']
                          },
              dataZoom: [
                {
                    type: 'inside',
                   realtime: true,
                     start: 0,
                    end: 50
                }
              ],
              xAxis: {
                axisLabel: {
                   rotate: 90,
                   fontSize: 10,
                },
                boundaryGap: false,      
                data: ['00:34', '01:34', '02:34', '03:34', '04:34', '05:34', '06:34', '07:34',
        '08:34', '09:34', '10:34', '11:34', '12:34', '13:34', '14:34', '15:34', '16:34',
        '17:34', '18:34', '19:34', '20:34'],
             
              },
              yAxis: {
                type: 'value',
                min: $_minTemperature,
                max: $_maxTemperature,
              },
              series: [
              {
                 name: 'Temperature',
                data: [37.7, 37.3, 38.2, 39.2, 39.8, 40, 39.8,
                  37.7, 37.3, 38.2, 39.2, 39.8, 40, 39.8, 
                  37.7, 37.3, 38.2, 39.2, 39.8, 40, 39.8, 
                ],
                type: 'line',
                color: 'blue',
              }
              ]
            }
          ''',
        ),
      ),
    );
  }
}
`

**Comment by entronad** [comment]
At top level of `Echarts()`

**Comment by Ghost180195** [comment]
@entronad Thank you very much! Everything is smooth now with captureHorizontalGestures: true 😉😉😉😉

**Comment by lironzemingo** [comment]
Hi, I too have a problem with the smooth scroll... I use 'inside' dataZoom, just like in the example above, and the Echart is inside a container. when scrolling horizontally, the elements on the chart don't seem to scroll smoothly, but rather look like they're rerendered every frame... it looks like the x-axis lables are changing and not scrolling. also added captureHorizontalGesture, but it doesn't seem to change anything.
I tried to put the chart in a SingleChildScrollView, but I get an error, since the parent widget has no size.
any idea how to solve this? if I put the chart in a scrollable widget - how do I do it? should I remove the DataZoom? tried few options, non worked. thanks.
