### ISSUE TITLE
iOS上，无法渲染图表

### ISSUE THREAD

**Issue by deboLing** [entronad/flutter_echarts#99]
1 在iOS真机上
2 在首页pageviwe的第二个页面加载 echarts组件，无法渲染图表
3 延时渲染也不行
不知为何？

**Comment by entronad** [comment]
Please see and discuss in this issue: #104 .

**Comment by entronad** [comment]
Please update to v2.1.0 and try setting `reloadAfterInit` to `true`.
Details discussed in https://github.com/entronad/flutter_echarts/issues/124 .
